name = "calebsmusic"
compatibility_date = "2026-07-29"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "calebs-music-db"
database_id = "0c202f0c-54c5-4f16-b43d-d71dbc520356"
